### ISSUE TITLE
Look up names in 'explicit' parser

### ISSUE THREAD

**Issue by S11001001** [ermine-language/ermine#15]
To implement its `undefined` hole, the `explicit` parser in `Ermine.Parser.Module` probably needs a stronger constraint. Or it may be impossible to write!

So we need to resolve that one way or the other, but we should be sure it's impossible to write like it is before we start rearranging.  We might need a type parameter on `Import` to support such a rearrangement.

**Comment by S11001001** [comment]
Awaiting test of `findGlobals`.

**Comment by joshcough** [comment]
findGlobals testing finished, test files in tests/test-files/parsing.
